module.exports = {
  projects: [
    '<rootDir>/apps/bike-store',
    '<rootDir>/libs/header',
    '<rootDir>/apps/todos',
    '<rootDir>/apps/todos-api',
    '<rootDir>/libs/data',
    '<rootDir>/libs/ui',
    '<rootDir>/apps/my-site',
    '<rootDir>/libs/ui-header',
    '<rootDir>/apps/my-site-api',
    '<rootDir>/libs/my-site-api-interface',
    '<rootDir>/apps/board-game-review',
    '<rootDir>/apps/board-game-review-api',
    '<rootDir>/apps/board-game-review-api-e2e',
    '<rootDir>/apps/board-game-review-e2e',
    '<rootDir>/libs/board-game-review-api-interface',
    '<rootDir>/libs/board-game-review/ui-tile',
    '<rootDir>/libs/board-game-review/util-formatters',
    '<rootDir>/libs/board-game-review/data-access-games',
    '<rootDir>/apps/board-game-store',
  ],
};
